---
abstract: 'bind c++ to perl'
author:
  - 'Tokuhiro Matsuno <tokuhirom ah! gmail.com>'
build_requires:
  Devel::CheckLib: 0
  ExtUtils::MakeMaker: 6.11
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-BindPP
no_index:
  directory:
    - inc
    - share
    - t
requires:
  File::Copy: 0
  File::ShareDir: 0
  Filter::Util::Call: 0
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tokuhirom/devel-bindpp.git
version: 0.05
